name: creating nuget
on:
 push:
  paths:
  - 'Ports/utils/**'
 workflow_dispatch:

# git diff HEAD~1 --name-only | xargs dirname | sed 's/Ports[/]//'

jobs:
  build:
    runs-on: windows-2019
    env:
      VCPKG_ROOT: 'C:/vcpkg'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: get vcpkg port name
        id: port-name
        run: |
          git status
          
      - name: install vcpkg package
        run: |
          vcpkg install opengl --overlay-ports="./ports"
          
      - name: export vcpkg package as nuget
        run: vcpkg export opengl --nuget
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: OpenglPackage
          path: ${{env.VCPKG_ROOT}}\*.nupkg
