name: creating nuget
on:
 push:
  paths:
  - '${{github.workspace}}/Ports/utils/**'
 workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    env:
      VCPKG_ROOT: 'C:/vcpkg'

    steps:
      - uses: actions/checkout@v3

      - name: install vcpkg package
        run: |
          vcpkg install opengl --overlay-ports="./ports"
          
      - name: export vcpkg package as nuget
        run: vcpkg export opengl --nuget
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: OpenglPackage
          path: ${{env.VCPKG_ROOT}}\*.nupkg
