name: creating nuget
on:
 push:
  paths:
  - 'Ports/opengl/**'
  branches:
  - main
 workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    env:
      VCPKG_ROOT: 'C:/vcpkg'
      ARCH: 'x64-windows'
      INSTALL_DIR: '${{github.workspace}}\out\install'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
         fetch-depth: '2'
        
      - name: get vcpkg port name
        id: port-getter
        run: |
          $port_name = git diff HEAD~1 --name-only
          $port_name = $port_name.split("/")[1]
          echo "PORT_NAME=$port_name" >> $env:GITHUB_OUTPUT
          echo $port_name
          
      - name: install vcpkg package
        run: vcpkg install ${{steps.port-getter.outputs.PORT_NAME}}:${{env.ARCH}} --overlay-ports="./ports"
          
      - name: export vcpkg package as nuget
        run: vcpkg export ${{steps.port-getter.outputs.PORT_NAME}}:${{env.ARCH}} --nuget
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{steps.port-getter.outputs.PORT_NAME}}_${{env.ARCH}}_nuget
          path: ${{env.INSTALL_DIR}}\package\*.nupkg
