name: creating nuget
on:
 push:
  paths:
  - 'Ports/opengl/**'
 workflow_dispatch:

# getting port in linux
# git diff HEAD~1 --name-only | xargs dirname | sed 's/Ports[/]//'

#$port_name = $port_name.split("/")[1]
#echo "{PORT_NAME}={ $port_name}" >> $GITHUB_ENV

jobs:
  build:
    runs-on: windows-2019
    env:
      VCPKG_ROOT: 'C:/vcpkg'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
         fetch-depth: '0'
        
      - name: get vcpkg port name
        run: |
          git diff ${{github.event.before}} ${{github.event.after}} --name-only
          
      - name: install vcpkg package
        run: |
          vcpkg install ${{env.PORT_NAME}} --overlay-ports="./ports"
          
      - name: export vcpkg package as nuget
        run: vcpkg export ${{env.PORT_NAME}} --nuget
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: OpenglPackage
          path: ${{env.VCPKG_ROOT}}\*.nupkg
